### ISSUE TITLE
MultiQC AtributeError: module has no attribute Mapping

### ISSUE THREAD

**Issue by SGMartin** [cnio-bu/varca#4]
```
AttributeError: module 'collections' has no attribute 'Mapping'
============================================================
[ERROR  ]         multiqc : Oops! The 'optitype' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module optitype raised an exception: Traceback (most recent call last):
  File "/home/sagarcia/varca_3rd_batch/.snakemake/conda/68d0e177db438e62b5590bd2ec57c5eb/lib/python3.11/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
             ^^^^^
  File "/home/sagarcia/varca_3rd_batch/.snakemake/conda/68d0e177db438e62b5590bd2ec57c5eb/lib/python3.11/site-packages/multiqc/modules/optitype/optitype.py", line 24, in __init__
    super(MultiqcModule, self).__init__(
  File "/home/sagarcia/varca_3rd_batch/.snakemake/conda/68d0e177db438e62b5590bd2ec57c5eb/lib/python3.11/site-packages/multiqc/modules/base_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/home/sagarcia/varca_3rd_batch/.snakemake/conda/68d0e177db438e62b5590bd2ec57c5eb/lib/python3.11/site-packages/multiqc/utils/config.py", line 250, in update
    return update_dict(globals(), u)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagarcia/varca_3rd_batch/.snakemake/conda/68d0e177db438e62b5590bd2ec57c5eb/lib/python3.11/site-packages/multiqc/utils/config.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Mapping'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by tdido** [comment]
This is a python version thing IIRC.
